# Generated by Django 4.2.1 on 2023-12-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, verbose_name='Location Name:')),
                ('location_address', models.TextField(verbose_name='Location Address')),
                ('location_phone', models.CharField(max_length=20, verbose_name='Location Phone Number')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Game Name')),
                ('short_name', models.CharField(max_length=10, verbose_name='Game Short Name')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('game_description', models.TextField(verbose_name='Detailed description')),
                ('game_steps', models.JSONField(default={'step': 'TBD'}, null=True)),
                ('game_props', models.JSONField(default={'prop': 'TBD'}, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.location')),
            ],
        ),
    ]
