# Generated by Django 4.2.1 on 2023-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_props',
            field=models.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_steps',
            field=models.JSONField(default={}, null=True),
        ),
    ]
