# Generated by Django 4.2.1 on 2023-12-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_games_game_props_alter_games_game_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_props',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_steps',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
