# Generated by Django 4.2.1 on 2023-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_games_game_props_alter_games_game_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='Descripiton', null=True),
        ),
    ]
