# Generated by Django 4.2.9 on 2024-01-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0004_location_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.CharField(default="Descripiton", max_length=200, null=True),
        ),
    ]
