# Generated by Django 4.2.1 on 2023-12-03 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0004_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EODReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Report Day')),
                ('game_status', models.JSONField(default=dict)),
                ('location_status', models.CharField(max_length=100)),
                ('games_served', models.IntegerField(default=0, verbose_name='Games Served')),
                ('location_cleaned_status', models.CharField(max_length=100)),
                ('eod_notes', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.location')),
            ],
        ),
    ]
