# Generated by Django 4.2.1 on 2024-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eodreport', '0003_endofdayreport_shift_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofdayreport',
            name='game_status',
            field=models.JSONField(default={'game_status': 'TBD'}),
        ),
    ]
