# Generated by Django 4.2.1 on 2024-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eodreport', '0004_endofdayreport_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofdayreport',
            name='game_status',
            field=models.JSONField(default={}),
        ),
    ]
