# Generated by Django 4.2.1 on 2024-01-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_location_description'),
        ('eodreport', '0006_alter_endofdayreport_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EODConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.location')),
            ],
        ),
        migrations.AlterField(
            model_name='endofdayreport',
            name='cash_in_box',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cash In the Box'),
        ),
        migrations.DeleteModel(
            name='EODGameStatus',
        ),
    ]
