# Generated by Django 4.2.9 on 2024-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eodreport", "0007_eodconfig_alter_endofdayreport_cash_in_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eodconfig",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eodconfig",
            name="distribution_list",
            field=models.JSONField(default=dict),
        ),
    ]
