# Generated by Django 4.2.9 on 2024-01-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eodreport", "0008_eodconfig_active_eodconfig_distribution_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdayreport",
            name="report_emailed",
            field=models.BooleanField(default=False),
        ),
    ]
