# Generated by Django 4.2.9 on 2024-01-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eodreport", "0009_endofdayreport_report_emailed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endofdayreport",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="endofdayreport",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="endofdayreport",
            name="report_date",
            field=models.DateField(auto_now_add=True, verbose_name="Report Day"),
        ),
    ]
