# Generated by Django 4.2.1 on 2023-06-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=200, unique=True, verbose_name='Booking ID')),
                ('listing', models.CharField(max_length=400, verbose_name='Listing Name')),
                ('arrival_date', models.DateTimeField(null=True, verbose_name='Arrival Date & Time')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_email', models.CharField(max_length=200, null=True, verbose_name='Customer Email')),
                ('guests', models.IntegerField(default=1, verbose_name='# Guests')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Base Amount')),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Taxes')),
                ('addons', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Taxes')),
                ('coupon_code', models.CharField(max_length=200, null=True, verbose_name='Coupon Code')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Amount')),
                ('adjustments', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Adjustments')),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total Value')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Revenue')),
                ('source', models.CharField(max_length=100, null=True, verbose_name='Booking Source ')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='Status')),
                ('booking_date', models.DateTimeField(null=True, verbose_name='Booking Date')),
                ('reserved_by', models.CharField(max_length=100, null=True, verbose_name='Reserved By')),
                ('confirmation_code', models.CharField(max_length=100, null=True, verbose_name='Confirmation Code')),
            ],
        ),
        migrations.DeleteModel(
            name='BOOKINGS',
        ),
    ]
