# Generated by Django 4.2.1 on 2023-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderbookings_delete_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbookings',
            name='location',
            field=models.CharField(default='Plano', max_length=100, verbose_name='Business Location'),
        ),
    ]
