# Generated by Django 4.2.1 on 2023-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderbookings_confirmation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField(auto_now=True, unique=True, verbose_name='Process Date')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('load_stats', models.JSONField(default={'count': 0})),
            ],
        ),
    ]
