# Generated by Django 4.2.1 on 2023-06-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_loadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadlog',
            name='load_stats',
            field=models.JSONField(default=dict),
        ),
    ]
